[deployment]
run = ["python3", "-m", "streamlit", "run", "streamlit_app.py", "--server.port", "5000", "--server.address", "0.0.0.0"]
deploymentTarget = "cloudrun"

[[ports]]
localPort = 5000
externalPort = 80