[run]
# Direct Streamlit command for proper deployment
command = ["python", "-m", "streamlit", "run", "streamlit_app.py", "--server.port", "5000", "--server.address", "0.0.0.0", "--server.headless", "true", "--browser.gatherUsageStats", "false"]

[deployment]
run = ["python", "main.py"]
deploymentTarget = "autoscale"
build = ["bash", "install.sh"]
publicDir = "/"

[nix]
channel = "stable-23.11"

[packager]
language = "python3"
ignoredPackages = ["uv"]

[packager.features]
enabledForHosting = false
packageSearch = false
guessImports = false

[[ports]]
localPort = 5000
externalPort = 80

[languages.python3]
pattern = "**/*.py"

[languages.python3.languageServer]
start = "pylsp"

# Environment variables for deployment
[env]
STREAMLIT_SERVER_PORT = "5000"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
UV_PYTHON = ""
UV_INSTALL = ""
DEPLOYMENT_METHOD = "pip"

# Deployment configuration
[deployment.health]
path = "/"
timeout = 30
period = 5